-- 0007_money_decisions.sql: founder money decisions of 2026-10-02 (docs/open-questions.md).
--   Q23a expense_payers         one bill, several payers
--   Q23c expenses.personal_member_id  personal-only expenses
--   Q21  expense_corrections    corrected state of settled expenses, for spending reports
--   Q24  expense_duplicate_reviews  organizer "keep both" on line-item duplicates
-- Generated by drizzle-kit, then made idempotent (IF NOT EXISTS / drop-then-add).
CREATE TABLE IF NOT EXISTS "expense_corrections" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"expense_id" uuid NOT NULL,
	"trip_id" uuid NOT NULL,
	"total_minor" bigint NOT NULL,
	"shares" jsonb NOT NULL,
	"paid_by_member_id" uuid NOT NULL,
	"payers" jsonb,
	"reason" text NOT NULL,
	"created_by_member_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "expense_duplicate_reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"trip_id" uuid NOT NULL,
	"expense_id" uuid NOT NULL,
	"other_expense_id" uuid NOT NULL,
	"decision" text NOT NULL,
	"decided_by_member_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "expense_payers" (
	"expense_id" uuid NOT NULL,
	"member_id" uuid NOT NULL,
	"paid_minor" bigint NOT NULL,
	CONSTRAINT "expense_payers_expense_id_member_id_pk" PRIMARY KEY("expense_id","member_id")
);
--> statement-breakpoint
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "personal_member_id" uuid;--> statement-breakpoint
ALTER TABLE "expense_corrections" DROP CONSTRAINT IF EXISTS "expense_corrections_expense_id_expenses_id_fk";--> statement-breakpoint
ALTER TABLE "expense_corrections" ADD CONSTRAINT "expense_corrections_expense_id_expenses_id_fk" FOREIGN KEY ("expense_id") REFERENCES "public"."expenses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_corrections" DROP CONSTRAINT IF EXISTS "expense_corrections_trip_id_trips_id_fk";--> statement-breakpoint
ALTER TABLE "expense_corrections" ADD CONSTRAINT "expense_corrections_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_corrections" DROP CONSTRAINT IF EXISTS "expense_corrections_paid_by_member_id_members_id_fk";--> statement-breakpoint
ALTER TABLE "expense_corrections" ADD CONSTRAINT "expense_corrections_paid_by_member_id_members_id_fk" FOREIGN KEY ("paid_by_member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_corrections" DROP CONSTRAINT IF EXISTS "expense_corrections_created_by_member_id_members_id_fk";--> statement-breakpoint
ALTER TABLE "expense_corrections" ADD CONSTRAINT "expense_corrections_created_by_member_id_members_id_fk" FOREIGN KEY ("created_by_member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_duplicate_reviews" DROP CONSTRAINT IF EXISTS "expense_duplicate_reviews_trip_id_trips_id_fk";--> statement-breakpoint
ALTER TABLE "expense_duplicate_reviews" ADD CONSTRAINT "expense_duplicate_reviews_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "public"."trips"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_duplicate_reviews" DROP CONSTRAINT IF EXISTS "expense_duplicate_reviews_expense_id_expenses_id_fk";--> statement-breakpoint
ALTER TABLE "expense_duplicate_reviews" ADD CONSTRAINT "expense_duplicate_reviews_expense_id_expenses_id_fk" FOREIGN KEY ("expense_id") REFERENCES "public"."expenses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_duplicate_reviews" DROP CONSTRAINT IF EXISTS "expense_duplicate_reviews_other_expense_id_expenses_id_fk";--> statement-breakpoint
ALTER TABLE "expense_duplicate_reviews" ADD CONSTRAINT "expense_duplicate_reviews_other_expense_id_expenses_id_fk" FOREIGN KEY ("other_expense_id") REFERENCES "public"."expenses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_duplicate_reviews" DROP CONSTRAINT IF EXISTS "expense_duplicate_reviews_decided_by_member_id_members_id_fk";--> statement-breakpoint
ALTER TABLE "expense_duplicate_reviews" ADD CONSTRAINT "expense_duplicate_reviews_decided_by_member_id_members_id_fk" FOREIGN KEY ("decided_by_member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_payers" DROP CONSTRAINT IF EXISTS "expense_payers_expense_id_expenses_id_fk";--> statement-breakpoint
ALTER TABLE "expense_payers" ADD CONSTRAINT "expense_payers_expense_id_expenses_id_fk" FOREIGN KEY ("expense_id") REFERENCES "public"."expenses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_payers" DROP CONSTRAINT IF EXISTS "expense_payers_member_id_members_id_fk";--> statement-breakpoint
ALTER TABLE "expense_payers" ADD CONSTRAINT "expense_payers_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "expense_corrections_expense_idx" ON "expense_corrections" USING btree ("expense_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "expense_duplicate_reviews_trip_idx" ON "expense_duplicate_reviews" USING btree ("trip_id");--> statement-breakpoint
ALTER TABLE "expenses" DROP CONSTRAINT IF EXISTS "expenses_personal_member_id_members_id_fk";--> statement-breakpoint
ALTER TABLE "expenses" ADD CONSTRAINT "expenses_personal_member_id_members_id_fk" FOREIGN KEY ("personal_member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;
