-- 0011_stop_geo.sql: Stops get a place on the map and a clock (FR-S6, FR-S9, FR-O8, FR-O15, FR-O16).
--   country_code / geocoded_name / geocode_source / geocoded_at  background geocoding of the Stop name
--   arrival_minute / departure_minute                            "We arrive Day 1 at 18:30", "We leave at 11:00"
-- (lat, lng and timezone already exist from 0000_init.)
-- Generated by drizzle-kit, then made idempotent (IF NOT EXISTS).
ALTER TABLE "stops" ADD COLUMN IF NOT EXISTS "country_code" text;--> statement-breakpoint
ALTER TABLE "stops" ADD COLUMN IF NOT EXISTS "geocoded_name" text;--> statement-breakpoint
ALTER TABLE "stops" ADD COLUMN IF NOT EXISTS "geocode_source" text;--> statement-breakpoint
ALTER TABLE "stops" ADD COLUMN IF NOT EXISTS "geocoded_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "stops" ADD COLUMN IF NOT EXISTS "arrival_minute" smallint;--> statement-breakpoint
ALTER TABLE "stops" ADD COLUMN IF NOT EXISTS "departure_minute" smallint;
