-- 0012_account_recheck.sql: account settings (Phase 1 slice 3).
--   FR-16 / J-4  users.recheck_pending_at  recycled-number check pending (email code or organizer confirms)
--   FR-3 / NFR-7 users.deleted_at          account deleted; the row stays, anonymized, for money history
-- Generated by drizzle-kit, then made idempotent (IF NOT EXISTS).
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "recheck_pending_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp with time zone;
